### ISSUE TITLE
Not Work for Wagtail 3.0

### ISSUE THREAD

**Issue by aliceni81** [wagtail/wagtail-autocomplete#115]
AutocompletePanel does not work any more if Wagtail version is upgraded to 3.0.

**Comment by th3hamm0r** [comment]
Fyi: I've created a quick PR #116 which fixes the compatibility with wagtail 3.0 for us.

**Comment by aliceni81** [comment]
Thanks @th3hamm0r 
I'm wondering whether there will be a new release compatible with Wagtail 3.0 soon.

**Comment by tuanth66** [comment]
Please update, I'm working with Wagtail 3.0 now :(

**Comment by nickmoreton** [comment]
I just worked on our Wagtail 3 upgrade to fix a couple of items that were holding this back.

[#121 ](https://github.com/wagtail/wagtail-autocomplete/pull/121)

Thanks @th3hamm0r for your [#116](https://github.com/wagtail/wagtail-autocomplete/pull/116) that helped a lot 👍

**Comment by andre-fuchs** [comment]
The pull request was merged two weeks ago, but the latest release is from 3 month ago. How can I get the version for Wagtail 3? ... I am jumping in circles on GitHub. Thanks for the guidance in advance.

**Comment by th3hamm0r** [comment]
@andre-fuchs as with every python package on github, you can always try to install a package from a git repository (see https://stackoverflow.com/a/13754517/1394330). Sometimes there are some required build-tasks (eg. generation of css/js files), then you will have to build it yourself and deploy that result somewhere. wagtail-autocomplete already contains the built files in the repository, so the following installation should work.
E.g. to install the merged commits from above, you could try to install it like:
```
pip install git+https://github.com/wagtail/wagtail-autocomplete.git@03f46a0c256989690d0a43fc21fe0f37f9ede765
```

I'm currently using a branch of my fork, which contains #116, but also #118 which fixes a coloring issue:
```
pip install git+https://github.com/th3hamm0r/wagtail-autocomplete.git@73a18bd43a5b08367d87061f152372abe486c821
```
Of course, as soon as a new release is published, you should better switch back to a clean installation from pypi.

**Comment by th3hamm0r** [comment]
This ticket can be closed @aliceni81, wagtail 3+ is supported since the release 0.9.0 (https://github.com/wagtail/wagtail-autocomplete/issues/125#issuecomment-1288554542).

**Comment by harrislapiroff** [comment]
Thanks, @th3hamm0r. Closing now.
