### ISSUE TITLE
Wagtail 3 support

### ISSUE THREAD

**Issue by nickmoreton** [wagtail/wagtail-autocomplete#125]
Hello,

I have submitted a PR https://github.com/wagtail/wagtail-autocomplete/pull/121 for Wagtail 3.0 support for this package.

Please can it be reviewed by someone. Thank you

**Comment by dustinblanchard** [comment]
Is there any timeline to get this reviewed and merged?

**Comment by stevil32** [comment]
Hello all. You're wonderful package looks like it will solve all of my problems once it's Wagtail 3.0+ ready. Is there any idea when that might be?

**Comment by th3hamm0r** [comment]
The wagtail 3 support has been released already with version 0.9.0, so the ticket can be closed @nickmoreton 
Fyi: We are using it with wagtail 4.0 without issues and we've also successfully tested it with the latest 4.1rc1 (#129).

**Comment by nickmoreton** [comment]
@th3hamm0r Great news thank you 👍

**Comment by stevil32** [comment]
Awesome package!
