### ISSUE TITLE
Add possibility to replace queryset filter with custom function

### ISSUE THREAD

**Issue by simon-retsch** [wagtail/wagtail-autocomplete#138]
### Description
We ran into the problem that a search term (on a non-wagtail page model) was resulting in more than 100 results that could therefore not be fully displayed. The entry we wanted to find was not included in the 100 items and therefore the search (icontains-filter) was not prioritizing our expected result.

### Suggestion
It would be great if one could implement a function like `autocomplete_custom_queryset_filter` in the model-to-search so that one can implement a different prioritization or improve the search in general as needed.

**Comment by simon-retsch** [comment]
Since we would need this functionality I already modified the necessary code locally so I could quickly create a PR for it, if this feature is approved to be added.

**Comment by rinti** [comment]
This would solve https://github.com/wagtail/wagtail-autocomplete/issues/120 too
