### ISSUE TITLE
Object of type 'UUID' is not JSON serializable

### ISSUE THREAD

**Issue by jcmundy** [wagtail/wagtail-autocomplete#46]
When I define out my AutocompletePanel and the special field, I get the error `Object of type 'UUID' is not JSON serializable`.  I am using a UUIDField as my pk 'id'.  Is there any way to get past this error?

**Comment by harrislapiroff** [comment]
Sorry for the long delay in responding to this. I actually don't have a lot of experience using non-default primary keys. Can you provide some example model code that I could look into?

**Comment by kutenai** [comment]
You will have to extend the JSON encoder and decoder. This isn't difficult but can be a bit complex to follow. I've never done it, so I can't provide an example, but here are some references that, combined, should get you there -- with some work.

Start with the json docs: https://docs.python.org/3/library/json.html

I found this reference that is NOT for Django but has some close similarities and could be useful to gain an understanding of the problem:
https://docs.python-eve.org/en/stable/tutorials/custom_idfields.html

Finally, you need to create a custom AutoCompleteWidget class and replace the serializer with your version that adds the serialization for UUID field.

`AutoComplete(Widget)` class does not have any hooks to change the serializer so you will need to override the methods `format_value` and `value_from_dict` to replace the default json.

**Comment by kutenai** [comment]
To complete what I am suggesting, you would need to do something like this:

```python
from wagtailautocomplete.edit_handlers import AutocompletePanel, _can_create
from wagtailautocomplete.widgets import Autocomplete as AutocompleteWidget


class AutocompleteWidgetExtended(AutocompleteWidget):
    """
    Generic override, keeps existing functionality
    ToDo: Extend to use custom json encoder
    """

    def format_value(self, *args, **kwargs):
        return super().format_value(*args, **kwargs)

    def value_from_datadict(self, *args, **kwargs):
        return super().value_from_datadict(*args, **kwargs)


class AutocompletePanelExtended(AutocompletePanel):

    def on_model_bound(self):
        """ This override replaces the widget with your custom version"""
        can_create = _can_create(self.target_model)
        self.widget = type(
            '_Autocomplete',
            (AutocompleteWidgetExtended,),
            dict(target_model=self.target_model, can_create=can_create, is_single=self.is_single),
        )
```

Provide a custom implementation for the converters in the widget to use a json serializer with UUID handling.

**Comment by jcmundy** [comment]
I am having this problem again.  I had managed to get around it by removing a line of code, but with our last wagtail update (I think) the error has returned.  Do the edits you suggest above go into widgets.py?

**Comment by jcmundy** [comment]
Sorry, I found my JSON Encoder had accidentally gotten deleted!  It's working again.

**Comment by deejungx** [comment]
I was having issues regarding this and the solutions mentioned above did not entirely work for me. I managed to solve the problem by changing the `widget_overrides` function instead of `on_model_bound`:

```python
import json

from django.core.serializers.json import DjangoJSONEncoder
from wagtailautocomplete.edit_handlers import (
    AutocompletePanel,
    _can_create,
    _is_single_value,
)
from wagtailautocomplete.views import render_page
from wagtailautocomplete.widgets import Autocomplete as AutocompleteWidget


class AutocompleteWidgetExtended(AutocompleteWidget):
    def format_value(self, value, *args, **kwargs):
        if not value:
            return "null"
        if type(value) == list:
            return json.dumps(
                [
                    render_page(page)
                    for page in self.target_model.objects.filter(pk__in=value)
                ],
                cls=DjangoJSONEncoder,
            )
        else:
            return json.dumps(
                render_page(self.target_model.objects.get(pk=value)),
                cls=DjangoJSONEncoder,
            )


class AutocompletePanelExtended(AutocompletePanel):
    def widget_overrides(self):
        return {
            self.field_name: AutocompleteWidgetExtended(
                target_model=self.target_model,
                can_create=_can_create(self.target_model),
                is_single=_is_single_value(self.db_field),
            )
        }

```
