### ISSUE TITLE
Support wagtail admin hosted at a different prefix

### ISSUE THREAD

**Issue by nwjlyons** [wagtail/wagtail-autocomplete#51]
`apiBase` is currently hardcoded https://github.com/wagtail/wagtail-autocomplete/blob/master/client/src/components/AutocompleteInput/index.js#L30

It would be good to support cases where the admin is hosted at a different prefix. eg `/cms/autocomplete/`

**Comment by pySilver** [comment]
+1, also bumped into hardcoded value.

**Comment by harrislapiroff** [comment]
Very good catch!

**Comment by Atum7** [comment]
+1

**Comment by adsk2050** [comment]
Please resolve this issue, I am also facing the same problem. Or in the meanwhile can you suggest some kind of workaround? Thanks a lot.

**Comment by t2y** [comment]
I also am waiting to resolve this issue.
