### ISSUE TITLE
queryset for AutocompletePanel

### ISSUE THREAD

**Issue by Fandekasp** [wagtail/wagtail-autocomplete#52]
Thank you for making AutocompletePanel, I look forward to see it merged in the core wagtail project.

I would like AutocompletePanel to only return a subset of objects from the target_model. Is that a feature you would be interested in implementing? Do you have a suggestion for an alternative way to handle this at the moment?

I was hoping that I could do something  like [ModelAdmin.get_queryset](http://docs.wagtail.io/en/v2.6.1/reference/contrib/modeladmin/indexview.html#modeladmin-get-queryset), to be able to filter depending on `request.user`

Currently using:
* Django==2.2.4
* wagtail==2.6.1
* wagtail-autocomplete==0.3.1

Edit: I asked the same question on [StackOverflow](https://stackoverflow.com/q/57552920/885053)

**Comment by Fandekasp** [comment]
I forgot that autocomplete fetches the data from ajax queries, and that I can write a view overriding autocomplete.Select2QuerySetView with a get_queryset. 
Will investigate tomorrow how to get the request.user in that method

**Comment by protasovse** [comment]
urlpatterns = [
    path('django-admin/', admin.site.urls, name='djangoadmin_home'),
    **path('admin/autocomplete/search/', require_admin_access(search)),**
    path('admin/autocomplete/', include(autocomplete_urls)),
    path('admin/', include(wagtailadmin_urls)),
    ...

и переписать функцию search...

**Comment by Fandekasp** [comment]
@protasovse I had to override the autocomplete search view and add my custom code within the view

**Comment by protasovse** [comment]
да... другого решения нет...

**Comment by protasovse** [comment]
> ```python
> queryset = my_custom_filter_function(queryset, model, request.user)  # CUSTOM
> ```

model - избыточно, его можно получить через queryset.model

> ```python
> queryset = my_custom_filter_function(queryset, request.user)  # CUSTOM
> ```
