### ISSUE TITLE
Support for Django 3

### ISSUE THREAD

**Issue by AdrienLemaire** [wagtail/wagtail-autocomplete#65]
wagtail 2.8 came up with support for django 3
https://github.com/wagtail/wagtail/blob/master/CHANGELOG.txt#L20

But when upgrading the packages, wagtail-autocomplete breaks:
```py
  File "/home/dori/.virtualenvs/project/lib/python3.8/site-packages/wagtailautocomplete/wagtail_hooks.py", line 1, in <module>
    from django.contrib.staticfiles.templatetags.staticfiles import static
ModuleNotFoundError: No module named 'django.contrib.staticfiles.templatetags'
```

As per https://stackoverflow.com/a/59935512, we need to import static from `django.templatetags.static` instead of `django.contrib.staticfiles.templatetags.staticfiles`

**Comment by AdrienLemaire** [comment]
Temporary fix: 
```console
$ sed -i 's/contrib.staticfiles.templatetags.staticfiles/templatetags.static/g' $VIRTUAL_ENV/lib/python3.8/site-packages/wagtailautocomplete/wagtail_hooks.py
```

**Comment by harrislapiroff** [comment]
Will be reviewing a PR to fix this (#63) later this week! Thanks for the report!

**Comment by AdrienLemaire** [comment]
Fyi, I didn't have other problems on local, but when deploying to production, I needed to add another fix in my container:
```console
$ sed -i 's/wagtail.admin.decorators/wagtail.admin.auth/g' /usr/local/lib/python3.8/site-packages/wagtailautocomplete/urls/admin.py
```

**Comment by AdrienLemaire** [comment]
@harrislapiroff you forgot to update `/wagtailautocomplete/urls/admin.py`

```diff
- from wagtail.admin.decorators import require_admin_access
+ from wagtail.admin.auth import require_admin_access
```

**Comment by harrislapiroff** [comment]
Good call. Since those paths appear to be preserved (though deprecated) through 2.8, I'm going to cut a release as is, but I will accept PRs making that fix at any time—particularly once we officially remove 2.3 support.

**Comment by Gulci** [comment]
FYI, Wagtail 2.9 has removed `wagtail.admin.decorators`.

https://github.com/wagtail/wagtail/commit/98e0dbcdabc33dfcfe9236ac67478a2dd4e56840
