### ISSUE TITLE
Needed release of package after release Wagtail 2.9

### ISSUE THREAD

**Issue by vThaian** [wagtail/wagtail-autocomplete#73]
The latest version of wagtail-autocomplete on the PyPi is 0.5 and is not working with Wagtail 2.9.

There is proper change on the master branch https://github.com/wagtail/wagtail-autocomplete/blob/master/wagtailautocomplete/urls/admin.py which fixes the issue below.

Error:
`ModuleNotFoundError: No module named 'wagtail.admin.decorators'`

require_admin_access since wagtail 2.9 not exists under wagtail.admin.decorators.

Could you please release a new version?

**Comment by bendison** [comment]
Would also really like to see an updated release for this same issue.

**Comment by harrislapiroff** [comment]
Done!
