### ISSUE TITLE
Add autocomplete=off to input elements

### ISSUE THREAD

**Issue by matthiasrohmer** [wagtail/wagtail-autocomplete#82]
Without `autocomplete=off` on the `<input>` element there can be a11y issues:

![Bildschirmfoto 2021-02-18 um 14 20 18](https://user-images.githubusercontent.com/12857772/108363235-fa495180-71f4-11eb-888c-b0f1cc629f76.png)

**Comment by harrislapiroff** [comment]
Oof, thanks for the report here!
