### ISSUE TITLE
Input text hidden behind search icon

### ISSUE THREAD

**Issue by ARogovskyy** [wagtail/wagtail-autocomplete#86]
The search text is hidden behind the search icon. It seems like the `paddin-left: 44px` property was overridden and thus not in effect.

Wagtail version: 2.12.2
Django version:  3.1.6
Wagtail autocomplete version: 0.6

![image](https://user-images.githubusercontent.com/48906414/111108019-49ff0c80-8558-11eb-8c5b-1a0711f5eec2.png)

**Comment by SaptakS** [comment]
@ARogovskyy this should be fixed once https://github.com/wagtail/wagtail-autocomplete/pull/84 is merged
