### ISSUE TITLE
Design is broken , search icon and input suggestions appearing in wrong positions

### ISSUE THREAD

**Issue by oladhari** [wagtail/wagtail-autocomplete#88]
the search icon and field suggestion are appearing in weird position since I updated to the newest version of wagtail-autocomplete

![Screenshot from 2021-03-18 10-56-46](https://user-images.githubusercontent.com/13581057/111562108-f4856280-87d8-11eb-866d-3bb88d7858b5.png)

Django==3.1.7
wagtail==2.12.3
wagtail-autocomplete==0.6.1

**Comment by ARogovskyy** [comment]
This seems to be a bug in the recently merged #84 . I commented on the probable cause

**Comment by oladhari** [comment]
> This seems to be a bug in the recently merged #84 . I commented on the probable cause

thank you for checking it fast

**Comment by SaptakS** [comment]
I just noticed my mistake in the PR. I will fix and send a new PR.

**Comment by SaptakS** [comment]
@ARogovskyy @oladhari https://github.com/wagtail/wagtail-autocomplete/pull/89/files should fix the isssue. Feel free to review, and let me know. Sorry for the stupid mistake I made.

**Comment by oladhari** [comment]
> @ARogovskyy @oladhari https://github.com/wagtail/wagtail-autocomplete/pull/89/files should fix the isssue. Feel free to review, and let me know. Sorry for the stupid mistake I made.

thank you for your efforts and thank you for fixing it so fast, that is really kind

**Comment by harrislapiroff** [comment]
I've cut a new release with fixes for this @ARogovskyy @oladhari. Thanks so much for the report and let us know if there's any trouble upgrading!

**Comment by oladhari** [comment]
thank you so much!
